name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Fish
        uses: fish-actions/install-fish@v1
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check
        run: just check
